// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using Moq;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State__Update_639985b94e
    {
        private Mock<State<IState>> _stateMock;

        [SetUp]
        public void Setup()
        {
            _stateMock = new Mock<State<IState>>();
        }

        [Test]
        public void _Update_WhenCalled_ShouldCallUpdateMethod()
        {
            // Arrange
            float deltaTime = 0.1f;

            // Act
            _stateMock.Object._Update(deltaTime);

            // Assert
            _stateMock.Verify(s => s.Update(deltaTime), Times.Once);
        }

        [Test]
        public void _Update_WhenCalledWithNegativeDeltaTime_ShouldThrowArgumentException()
        {
            // Arrange
            float deltaTime = -0.1f;

            // Act & Assert
            Assert.Throws<ArgumentException>(() => _stateMock.Object._Update(deltaTime));
        }
    }
}
