// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateChangeEventArgs_Tests
    {
        private FiniteStateChangeEventArgs _finiteStateChangeEventArgs;

        [SetUp]
        public void SetUp()
        {
            _finiteStateChangeEventArgs = new FiniteStateChangeEventArgs(StateType.Init);
        }

        [Test]
        public void Constructor_ShouldSet_RequestedType()
        {
            // Arrange
            var expectedState = StateType.Init;

            // Act
            var result = _finiteStateChangeEventArgs.RequestedType;

            // Assert
            Assert.AreEqual(expectedState, result);
        }

        [Test]
        public void Constructor_ShouldSet_RequestedType_ToDifferentState()
        {
            // Arrange
            var expectedState = StateType.Process;

            // Act
            _finiteStateChangeEventArgs = new FiniteStateChangeEventArgs(expectedState);
            var result = _finiteStateChangeEventArgs.RequestedType;

            // Assert
            Assert.AreEqual(expectedState, result);
        }

        [Test]
        public void Constructor_ShouldThrowException_WhenNullStatePassed()
        {
            // Arrange
            StateType? stateType = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateChangeEventArgs(stateType));
        }
    }
}
