// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateBeganEventArgs_FiniteStateBeganEventArgs_9169a2778c
    {
        [Test]
        public void FiniteStateBeganEventArgs_WithValidStateType_SetsTypeCorrectly()
        {
            // Arrange
            var expectedStateType = StateType.Valid; // Assuming 'Valid' is a valid state in 'StateType' enum

            // Act
            var eventArgs = new FiniteStateBeganEventArgs(expectedStateType);

            // Assert
            Assert.AreEqual(expectedStateType, eventArgs.Type);
        }

        [Test]
        public void FiniteStateBeganEventArgs_WithInvalidStateType_ThrowsException()
        {
            // Arrange
            var invalidStateType = (StateType)999; // Assuming 999 is not a valid state in 'StateType' enum

            // Act & Assert
            Assert.Throws<ArgumentException>(() => new FiniteStateBeganEventArgs(invalidStateType));
        }
    }
}
