// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    public class FiniteStateMachine_MoveTo_e3f88cdb76
    {
        private FiniteStateMachine _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _finiteStateMachine = new FiniteStateMachine();
        }

        [Test]
        public void MoveTo_ValidTargetStateKey_ReturnsTargetStateKey()
        {
            // Arrange
            StateType targetStateKey = new StateType();

            // Act
            var result = _finiteStateMachine.MoveTo(targetStateKey);

            // Assert
            Assert.AreEqual(targetStateKey, result);
        }

        [Test]
        public void MoveTo_InvalidTargetStateKey_ThrowsException()
        {
            // Arrange
            StateType targetStateKey = new StateType(); // TODO: Set an invalid state key

            // Act & Assert
            Assert.Throws<Exception>(() => _finiteStateMachine.MoveTo(targetStateKey));
        }

        [Test]
        public void MoveTo_ValidTargetStateKey_FiresOnStateChange()
        {
            // Arrange
            StateType targetStateKey = new StateType();
            bool eventFired = false;
            _finiteStateMachine.OnStateChange += (args) => eventFired = true;

            // Act
            _finiteStateMachine.MoveTo(targetStateKey);

            // Assert
            Assert.IsTrue(eventFired);
        }
    }
}
