// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Initialize_99e1f35a6a
    {
        private StateMachine<string> _stateMachine;

        [SetUp]
        public void Setup()
        {
            _stateMachine = new StateMachine<string>();
        }

        [Test]
        public void Initialize_WhenCalled_ShouldNotThrowException()
        {
            Assert.DoesNotThrow(() => _stateMachine.Initialize());
        }

        [Test]
        public void Initialize_WhenCalled_ShouldSetProperInitialState()
        {
            // TODO: Replace 'ExpectedInitialState' with the actual initial state expected after initialization
            var ExpectedInitialState = "ExpectedInitialState";

            _stateMachine.Initialize();

            Assert.AreEqual(ExpectedInitialState, _stateMachine.CurrentState);
        }

        [TearDown]
        public void Cleanup()
        {
            _stateMachine = null;
        }
    }
}
