// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateBaseEndTest
    {
        private StateBase _stateBaseEnd;
        private FiniteStateMachine _finiteStateMachine;

        [SetUp]
        public void Setup()
        {
            _stateBaseEnd = new StateBase();
            _finiteStateMachine = FiniteStateMachine.Instance;
            _finiteStateMachine.OnStateEnded = null;
        }

        [Test]
        public void Test_End_WhenCalled_ShouldInvokeEndMethod()
        {
            // Arrange
            bool isEndCalled = false;
            _stateBaseEnd.End = () => { isEndCalled = true; };

            // Act
            _stateBaseEnd.End();

            // Assert
            Assert.IsTrue(isEndCalled);
        }

        [Test]
        public void Test_End_WhenCalled_ShouldInvokeOnStateEndedEvent()
        {
            // Arrange
            bool isEventTriggered = false;
            _finiteStateMachine.OnStateEnded += (args) => { isEventTriggered = true; };

            // Act
            _stateBaseEnd.End();

            // Assert
            Assert.IsTrue(isEventTriggered);
        }

        [Test]
        public void Test_End_WhenOnStateEndedIsNull_ShouldNotThrowException()
        {
            // Arrange
            _finiteStateMachine.OnStateEnded = null;

            // Act & Assert
            Assert.DoesNotThrow(() => _stateBaseEnd.End());
        }
    }
}
