// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;
using Moq; // Added this to resolve the error related to Mock

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class StateMachine_Update_73a5496b2c
    {
        private StateMachine<int> stateMachine; // Added generic type to resolve the error related to StateMachine
        private Mock<IState<int>> mockState; // Added generic type to resolve the error related to IState

        [SetUp]
        public void Setup()
        {
            // Arrange
            mockState = new Mock<IState<int>>(); // Adjusted this to match the new type of mockState
            stateMachine = new StateMachine<int>(); // Adjusted this to match the new type of stateMachine
        }

        [Test]
        public void Update_WithCurrentState_CallsUpdateOnCurrentState()
        {
            // Arrange
            stateMachine.SetState(mockState.Object);

            // Act
            stateMachine.Update(1);

            // Assert
            mockState.Verify(s => s._Update(1), Times.Once);
        }

        [Test]
        public void Update_WithoutCurrentState_DoesNotThrowException()
        {
            // Act and Assert
            Assert.DoesNotThrow(() => stateMachine.Update(1));
        }

        [Test]
        public void Update_WithNegativeDeltaTime_ThrowsArgumentOutOfRangeException()
        {
            // Arrange
            stateMachine.SetState(mockState.Object);

            // Act and Assert
            Assert.Throws<ArgumentOutOfRangeException>(() => stateMachine.Update(-1));
        }

        [TearDown]
        public void Teardown()
        {
            stateMachine = null;
            mockState = null;
        }
    }
}
