// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;
using System;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class State_State_f11a4f0491
    {
        private StateMachine<int> _fsm;
        private State<int> _state;
        private int _stateKey;

        [SetUp]
        public void SetUp()
        {
            _fsm = new ConcreteStateMachine();
            _stateKey = 1;
            _state = new ConcreteState(_fsm, _stateKey);
        }

        [Test]
        public void State_Constructor_ValidParameters_ShouldNotThrowException()
        {
            Assert.DoesNotThrow(() => new ConcreteState(_fsm, _stateKey));
        }

        [Test]
        public void State_Constructor_NullStateMachine_ShouldThrowArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new ConcreteState(null, _stateKey));
        }

        [Test]
        public void State_Constructor_ValidParameters_StateMachinePropertyShouldBeSet()
        {
            Assert.AreEqual(_fsm, _state.StateMachine);
        }

        [Test]
        public void State_Constructor_ValidParameters_StateKeyPropertyShouldBeSet()
        {
            Assert.AreEqual(_stateKey, _state.StateKey);
        }
    }

    public class ConcreteStateMachine : StateMachine<int>
    {
        // Implement the abstract methods and properties here
    }

    public class ConcreteState : State<int>
    {
        public ConcreteState(StateMachine<int> fsm, int stateKey) : base(fsm, stateKey)
        {
            // Implement the abstract methods and properties here
        }
    }
}
