// Test generated by RoostGPT for test CsharpUnitTest using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using FiniteStateMachine;

namespace FiniteStateMachine.Test
{
    [TestFixture]
    public class FiniteStateEndedEventArgs_FiniteStateEndedEventArgs_8c2093187a
    {
        [Test]
        public void FiniteStateEndedEventArgs_StateTypeIsDefault_ThrowsArgumentNullException()
        {
            // Arrange
            StateType endedState = default;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new FiniteStateEndedEventArgs(endedState));
        }

        [Test]
        public void FiniteStateEndedEventArgs_StateTypeIsValid_SetsTypeProperty()
        {
            // Arrange
            StateType endedState = new StateType();

            // Act
            var result = new FiniteStateEndedEventArgs(endedState);

            // Assert
            Assert.AreEqual(endedState, result.Type);
        }
    }
}
